### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by sun744-cmd** [laiguokun/LSTNet#21]
Traceback (most recent call last):
  File "main.py", line 149, in <module>
    train_loss = train(Data, Data.train[0], Data.train[1], model, criterion, optim, args.batch_size)
  File "main.py", line 60, in train
    total_loss += loss.data[0];
IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number

**Comment by RiekeZoe** [comment]
I had the same problem. This can be solved by simply removing the [0], as suggested by @huangbiubiu here https://github.com/NVIDIA/flownet2-pytorch/issues/113. When you implement this and run the code, you will encounter a few more errors of the same origin, so you probably have to do the same again. Alternatively  you could also use an old version of PyTorch that still uses the 0-index. 

Old code: total_loss += loss.data[0];
New code: total_loss += loss.data
